services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
  frontend:
    extends:
      file: ./todo-frontend/docker-compose.yml
      service: app
    build:
      args:
        - BACKEND_URL=http://localhost:8080/api/
  backend:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: server
  mongo:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: mongo
  redis:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: redis
